import React, { Component } from "react";
import TagManager from 'react-gtm-module'

class Condiciones extends Component {

  componentDidMount(){
    const tagManagerArgs = {
      gtmId: 'GTM-TS2LLGT',
      dataLayer:{
        event: 'pageview'
      }
    }
    TagManager.initialize(tagManagerArgs)
  }


  render() {
    return (
      <div className="container">

        <div>
          <h1 className="titulo bases">BASES Y <br className="espacioBases"></br>CONDICIONES</h1>
        </div>
        <div className="nubesContainer">
        <div className="nube nubeFaq">
          <span className="resp">
            <ol className="contenedorTerminos">

<li>Mondelez Uruguay S.A. (el “Organizador”) organiza la promoción denominada "SUPER PROMO TANG“ (la “Promoción”), que tendrá vigencia en todo el territorio de la República Oriental del Uruguay (el “Territorio”) entre el 1º de junio de 2019 y el 15 de setiembre de 2019 (el “Plazo de Vigencia”) y se regirá por lo establecido en estas bases y condiciones (las “Bases”). </li>
<li>Participan en la Promoción los polvos para preparar bebidas comercializados por el Organizador bajo la marca “Tang”, en todos sus sabores y tamaños de envase, obre o no en tales envases publicidad de la Promoción (“Producto/s Participante/s”).</li>
<li>Podrán participar en la Promoción todas aquellas personas mayores de 13 años, de cualquier nacionalidad, que residan en el Territorio. No podrán participar en la Promoción: (i) personas jurídicas, (ii) personas menores de 13 años, (iii) personas domiciliadas fuera del Territorio, ni (iv) personal del Organizador, de sus agencias de publicidad y promociones, sus parientes por consanguinidad o afinidad hasta el segundo grado inclusive ni sus cónyuges.</li>
<li>Para participar en la Promoción los interesados que cumplan con los requisitos indicados en el punto 3., precedente (“Participante/s”), deberán, durante el Plazo de Vigencia, conectarse a través de la aplicación WhatsApp al número telefónico 096 700 148 (“Línea/s WhatsApp”) o ingresar en el sitio Web www.promo-tang.com (el “Sitio Web”). Cuando la participación en la Promoción se efectúe a través de una Línea WhatsApp, una vez establecida la comunicación el Participante deberá (i) Enviar a la Línea WhatsApp un mensaje con las palabras QUIERO MAS, (ii) Informar a la Línea WhatsApp los datos personales que se le requerirán (“Datos Personales”) y aceptar las Bases de la Promoción y (iii) Ingresar el código impreso en el envase de uno cualquiera de los Productos Participantes, a partir de la letra L y los siete (7) dígitos siguientes (“Código/s” y conjuntamente con los Datos Personales, los “Datos”). Cuando la participación en la Promoción se efectúe a través del Sitio Web el Participante deberá (a) Cargar en el Sitio Web los datos personales que se le requerirán (también “Datos Personales”) y aceptar las Bases de la Promoción y (b) Al igual que lo establecido en el ítem (iii), precedente, Ingresar un Código (los Códigos conjuntamente con los Datos Personales, también los “Datos”). Quedarán excluidos de la Promoción los Participantes que no hayan completado la totalidad de los Datos o cuyos Datos sean erróneos o falsos y los que no hayan aceptado estas Bases. Los Participantes podrán ingresar un mismo Código un máximo de diez (10) veces en un mismo día y hasta un máximo de veinte (20) veces durante el Plazo de Vigencia.</li>
<li>Completados los Datos a través de la Línea de WhatsApp o del Sitio Web, conforme lo  indicado en el punto 4., precedente, los Participantes participarán automática e inmediatamente en un sorteo   de resolución inmediata (“Sorteo/s Inmediato/s”). Mediante los Sorteos Inmediatos se pondrán en juego: (i) Una (1) televisión Samsung, modelo 55MU6100, con pantalla de 55´ + un (1) “home theater” “Sony 5.1 BDV-E4100” (“TV + HT”), (ii) Un (1) teléfono celular “Samsung Galaxy”, “A7” 64 GB (“Teléfono”), (iii) Un (1) Smartwatch “Samsung”, “FIT 2 PRO” (“Smartwatch”), (iv) Una (1) computadora tipo “Tablet” “Samsung Galaxy”, “TAB”, con pantalla de siete (7) pulgadas (“Tablet/s”), (v) Cinco (5) Auriculares Bluetooth “Sony”, “MDR-ZX220BT” (“Auricular/es”), (vi) Seis (6) Parlantes Bluetooth “Philips” “BT25-BX/77” (“Parlante/s” y conjuntamente con el TV + HT, los Teléfonos,  los Smartwatches, las Tablets, los Auriculares, los “Premios” e individualmente un “Premio”). </li>
<li>La asignación del carácter de potencial ganador de los Premios Inmediatos estará predeterminada en un programa de computación (“Software”), que contendrá para cada día del Plazo de Vigencia los horarios ganadores para cada uno de los Premios Inmediatos puestos en juego (“Horario/s Ganador/es”). Cuando un Participante participe en un Sorteo Inmediato en uno de los Horarios Ganadores se constituirá en el potencial ganador de uno de los Premios Inmediatos (también, “Potencial/es Ganador/es”). En el caso de que ningún Participante participase de un Sorteo Inmediato en un determinado Horario Ganador, el Potencial Ganador del Premio Inmediato atribuido a dicho Horario Ganador será el primer participante que participe en la Promoción con posterioridad al Horario Ganador vacante. Los Horarios Ganadores han sido establecidos por el Organizador, ante escribano público, con anterioridad al comienzo de la Promoción. El Organizador ha depositado ante escribano público copia de dichos Horarios Ganadores y, en consecuencia, no reconocerá como Horario Ganador a ninguno distinto de los depositados.</li>
<li>Los Premios no incluyen ningún otro pago, prestación, bien o servicio distinto de lo detallado en estas Bases, el derecho a su asignación es intransferible, no podrá exigirse su canje por dinero u otros bienes o servicios.</li>
<li>Los Participantes deberán conservar los envases de los Productos Participantes cuyos Códigos hubiesen utilizado para participar de la Promoción (“Envases”). Los Potenciales Ganadores serán notificados de su carácter de tales mediante el envío de un mensaje de WhatsApp o mediante el envío de un mail, de acuerdo con la forma en que hubiesen participado de la Promoción (la “Notificación”), que incluirá un código numérico o alfanumérico (“Código de Autenticación”) y deberán reclamar la asignación de los Premios y coordinar la fecha en que contestarán las preguntas de cultura general que les formulará el Organizador como uno de los requisitos de asignación de los Premios, dentro de los cinco (5) días de notificados, de lunes a viernes, en días hábiles, de 12:00 17:00 hs., llamando al teléfono 26828259 o al teléfono Celular : 099566869, momento en el que deberán (i) informar los datos personales que se les requerirán y (ii) enviar por mail, dentro del mismo plazo, a la dirección electrónica desde la cual se les enviara la Notificación, una fotografía de los Envases cuyos Códigos hubiesen utilizado para participar de la Promoción, sin perjuicio de que el Organizador podrá requerir el envío por correo de los Envases originales. </li>
<li>La falta de reclamo de la asignación de los Premios dentro del plazo y en la forma indicada en el punto precedente o – cuando corresponda - la contestación incorrecta a más de una (1) de las cinco (5) preguntas de cultura general que les formulará el Organizador o la falta de envío de una fotografía de los Envases o de los Envases originales o la negativa a presentarse a sesiones de fotografía o filmación que eventualmente les requiera el Organizador o el incumplimiento de cualquier otra de las condiciones de asignación establecidas en estas Bases hará perder a los Potenciales Ganadores, automáticamente, el derecho a la asignación de los Premios. Los Premios no asignados a ganador alguno, si los hubiera, quedarán en propiedad del Organizador. </li>
<li>Todos los costos que se deriven de la participación en la Promoción como así también los gastos, sin limitación, en que incurran los Potenciales Ganadores para reclamar la asignación de los Premios, estarán a su exclusivo cargo. </li>
<li>Los Premios serán entregados dentro de los sesenta (60) días corridos de la asignación de cada uno de ellos, en fecha y horario acordados previamente entre el Potencial Ganador y el Organizador. Los premios deberán ser retirados en la calle Divina Comedia 1651, en el horario de 11 hs a 17 hs. en de la Ciudad de Montevideo. El Organizador podrá remitir uno o más Premios por correo a los domicilios de los Potenciales Ganadores que residan a más de setenta (70) kilómetros de la ciudad de Montevideo. En caso de que el correo concurriera en más de dos (2) oportunidades y el Potencial Ganador no se encontrara disponible para exhibir su cedula de identidad y entregar una fotocopia del mismo, contestar – cuando corresponda - las preguntas de cultura general, firmar la autorización de uso de imagen y recibir el Premio, dicho Potencial Ganador perderá automáticamente el derecho a que el Premio le sea asignado.</li>
<li>Está prohibido y será anulado cualquier intento o método de participación en la Promoción que se realice por cualquier proceso, técnica o mecánica de participación distinta a la detallada en estas Bases. La utilización de técnicas de naturaleza robótica, repetitiva, automática, programada, mecanizada o similar llevará a la anulación de todas las participaciones del Participante. La participación de los Participantes en la Promoción podrá ser cancelada en cualquier momento, a exclusivo criterio del Organizador, si se comprobase o razonablemente pudiera deducirse que una o más de las participaciones efectuadas por el Participante lo fueron fraudulentamente; por ejemplo mediante la utilización de sistemas automáticos. </li>
<li>Los Datos Personales de los Participantes serán incluidos en una base de datos Personales por Mondelez Argentina S.A. </li>
<li>Sin obligación de compra. A las personas mayores de 13 años, residentes en el Territorio, que envíen un mail, durante el Plazo de Vigencia, a la dirección de correo electrónico consultas.uy@mdlz.com con el Asunto: Promoción “SUPER PROMO TANG”, el Organizador les remitirá, por el mismo medio, un Código que les permitirá participar de la Promoción. Se remitirá, como máximo, un (1) Código por día, por persona. </li>
<li>Ningún Participante podrá ganar más de un (1) Premio. La probabilidad de constituirse en Potencial Ganador de un Premio dependerá de la cantidad de Premios puestos en juego un día determinado y de la cantidad de Participantes que participen ese día. En el supuesto que un día determinado del Plazo de Vigencia hubiesen participado en los Sorteos Inmediatos dos mil (2.000) Participantes y se hubiesen puesto en juego 4 Premios, la probabilidad de tal Participante de resultar favorecido con un Premio sería de 1 en 500.</li>
<li>Será a cargo de los ganadores todo impuesto, tasa o contribución que deba tributarse sobre o en relación con los Premios Los gastos en que incurran los Potenciales Ganadores cuando concurran a reclamar la asignación o a retirar los Premios estarán asimismo a su exclusivo cargo.</li>
<li>La participación en la Promoción implica por parte de los Participantes la autorización por el plazo de un (1) año, contados desde el comienzo del Plazo de Vigencia, para la publicación y difusión de sus datos e imágenes, con fines comerciales, en los medios que el Organizador disponga, existentes en la actualidad y los que pudieran existir en el futuro, en cualquier parte del mundo, a título gratuito y su compromiso de no revocar dicha autorización. Como requisito para la asignación de los Premios, los Potenciales Ganadores deberán suscribir la documentación que el Organizador les requiera para permitir la utilización de sus imágenes en los términos previstos en éste punto sin derecho a compensación de ningún tipo. </li>
<li>La participación en la Promoción implica una declaración jurada de los Participantes en el sentido de que (i) No han cedido a terceros los derechos de publicación o reproducción de sus nombres o imágenes y (ii) Mantendrán indemne al Organizador de cualquier reclamo que éste pudiera recibir de cualquier tercero con relación a o con motivo de la publicación o reproducción de sus nombres o imágenes.</li>
<li>El Organizador no será responsable: (i) por ningún daño o perjuicio, de cualquier tipo que fuere, que pudieren sufrir los Participantes o los ganadores, en sus personas o bienes, con motivo de o con relación a su participación en la Promoción, la asignación y utilización de los Premios; (ii) por fallas de los equipos de comunicación, de la red Internet, de suministro de energía, de las líneas telefónicas, ni (iii) por desperfectos técnicos, errores humanos o acciones deliberadas de terceros que pudieran interrumpir o alterar el normal desarrollo de la Promoción o causar daños en los equipos o software de los Participantes. </li>
<li>WhatsApp no tiene intervención ni responsabilidad alguna en la organización de la Promoción. En consecuencia, WhatsApp no será responsable del cumplimiento de los compromisos que asume el Organizador en estas Bases y los Potenciales Ganadores deberán reclamar la asignación y entrega de los Premios exclusivamente al Organizador.</li>
<li>El Organizador podrá ampliar la cantidad de premios ofrecidos y/o el Plazo de Vigencia. Cuando circunstancias no imputables al Organizador o no previstas en estas Bases o que constituyan caso fortuito o fuerza mayor lo justifiquen, el Organizador podrá suspender, cancelar o modificar la Promoción, supuesto en el cual los Participantes no tendrán derecho a reclamo alguno. Toda modificación que se realice a estas Bases será sin alterar la esencia de la Promoción.</li>
<li>La participación en la Promoción implica la aceptación de estas Bases y de las decisiones que adopte el Organizador, conforme a derecho, sobre cualquier cuestión relacionada con la misma. </li>
<li>Para cualquier cuestión judicial que pudiera derivarse de la realización de la Promoción, los Participantes y el Organizador se someterán a la jurisdicción de los tribunales de Montevideo, , República Oriental del Uruguay. </li>
<li>La participación en esta promoción implica el conocimiento y aceptación de estas bases en su totalidad.</li>
<li>Estas Bases se encontrarán disponibles durante el Plazo de Vigencia en el Sitio Web www.promo-tang.com </li>

</ol>
          </span>
          <div className="triangleFaq"></div>
        </div>
      </div>
      </div>


    );
  }
}

export default Condiciones;
